---
apiVersion: v1
kind: Service
metadata:
  name: workers
  labels:
    app.kubernetes.io/name: workers
    app.kubernetes.io/instance: workers
    app.kubernetes.io/version: "2.2.2"
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: workers
    app.kubernetes.io/instance: workers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  labels:
    app.kubernetes.io/name: workers
    app.kubernetes.io/instance: workers
    app.kubernetes.io/version: "2.2.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: workers
      app.kubernetes.io/instance: workers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: workers
        app.kubernetes.io/instance: workers
    spec:
      # securityContext:
      #   runAsUser: 1000
      containers:
        - name: workers
          image: "workers:skf"
          imagePullPolicy: Never
          env:
          -  name: RABBIT_MQ_CONN_STRING
             valueFrom:
               configMapKeyRef:
                 name: rabbitmq
                 key: RABBIT_MQ_CONN_STRING
          -  name: RABBITMQ_DEFAULT_USER
             valueFrom:
               configMapKeyRef:
                 name: rabbitmq
                 key: RABBITMQ_DEFAULT_USER
          -  name: RABBITMQ_DEFAULT_PASS
             valueFrom:
               configMapKeyRef:
                 name: rabbitmq
                 key: RABBITMQ_DEFAULT_PASS
          -  name: KUBERNETES_HOST
             valueFrom:
               configMapKeyRef:
                 name: workers
                 key: KUBERNETES_HOST
          -  name: KUBECONFIG
             valueFrom:
               configMapKeyRef:
                 name: workers
                 key: KUBECONFIG
          -  name: SKF_LABS_DOMAIN
             valueFrom:
               configMapKeyRef:
                 name: workers
                 key: SKF_LABS_DOMAIN
          -  name: SKF_LABS_DEPLOY_MODE
             valueFrom:
               configMapKeyRef:
                 name: workers
                 key: SKF_LABS_DEPLOY_MODE
---
